github/developer.github.com

- content/libraries.md
This PR adds another Erlang lib to the list of wrappers.
> Add reference to octo.erl

- content/v3.md
From [the documentation](https://github.com/github/developer.github.com/blob/1aaa1d1ebcea67922ee2df12e1ec38d27ae87fa0/content/v3.md):
```curl
PUT /repos/:owner/:repo/pulls/:number/merge
```
Custom actions are using `PUT` instead of `POST`.
> Fix verbs description concerning custom actions

- content/guides/managing-deploy-keys.md
I'll be the first to admit my changes here are a bit of a guess, but I believe I'm correctly clarifying a concept that wasn't previously clear (at least in this document):
Only through the use of teams can one grant read-only access to a repository.
Teams are only available to organizations.
> Clarify access granted by deploy keys vs teams vs collaborators.

- content/v3/activity.md
Updated Activity page so that section descriptions match the order found in the contents selector on the side.
Just makes it a bit easier to browse the docs :thumbsup:.
> Fixed ordering of Activity API overview headers

- content/v3/licenses.md
- layouts/sidebar.html
* Adds Licenses to the API menu sidebar
* Refers to `:owner/:repo`, which is what we do across the API (e.g. `GET /repos/:owner/:repo/commits`)
/cc @github/docs-platform @benbalter
> Licensee cleanup

- content/guides/using-ssh-agent-forwarding.md
Max OS X does not add ssh keys automatically on login, but there is an easy fix.
> Add Paragraph to attack a common Mac OS X problem

- content/changes/2012-12-06-create-authorization-for-app.html
- content/v3/activity.md
- content/v3/activity/feeds.md
Use "authenticated user" instead of "authenticating user".
---
In this context I'm almost sure it should be *authenticated user* (it's already used in the list below next to the description).
However there are [some other cases when this is used](https://github.com/github/developer.github.com/search?utf8=%E2%9C%93&q=authenticating+user).
- https://github.com/github/developer.github.com/blob/9c97519f8cf8963305104fe18c8f67fef20295fb/content/changes/2012-12-06-create-authorization-for-app.html#L17
- https://github.com/github/developer.github.com/blob/9c97519f8cf8963305104fe18c8f67fef20295fb/content/v3/activity.md#feeds
I will fix them too if you consider that. :smile:
> Fixed typo in the "List feeds" description

- content/v3/activity/feeds.md
Most probably that was a typo.
---
Apparently I learned [a new word](http://en.wiktionary.org/wiki/revokable), but I'm not sure how fine is that. :smile:
> Use "revocable" instead of "revokable"

- content/v3/search.md
In the curl examples, URLs containing ampersands need to be quoted to avoid bash swallowing part of them.
> Make lazy search developers happy

- content/v3/search.md
It wasn't immediately clear that the qualifiers on the Search API page are links to further documentation. Links to the two in-browser search syntax documents have been added. The `forks` qualifiers was also separated from the `fork` qualifier as described on the search doc page.
> Make search syntax documentation more obvious

- content/libraries.md
This is a simple Object Oriented wrapper for GitHub API v3, written with PHP5.
This library works with cURL and provides all documented functionality as described in the official documentation including Client and WebHooks.
> Adding GitHub API v3 new PHP wrapper

- content/libraries.md
I will also add a line at the bottom of the page indicating that this list is editable here if you think that's OK. I sent a GitHub API support email that @izuzak was kind enough to respond to that wouldn't have been sent if I knew that this list was editable like the API docs. I guess I should have assumed it was...
> ownership of ocaml-github changed

- content/v3/oauth.md
- content/v3/repos/collaborators.md
Found out that that the scope `public_repo` or `repo` was required to make this api request properly. Otherwise the api results in 
```
403 Forbidden
{
"message": "Must have push access to view repository collaborators.",
"documentation_url": "https://developer.github.com/v3"
}
```
I hope this changes in the future. Adding this note to the documentation would have helped.
> Added note about acting user scope

- content/v3/repos/releases.md
The `label` parameter assigns the human-readable label for the uploaded asset. This parameter is already documented for the "Edit" endpoint, but was never documented for "Create".
> Document `label` parameter when creating release asset

- content/v3/oauth.md
> Explain `state` in "GitHub redirects back to your site" step of OAuth documentation

- content/v3/repos/forks.md
The existing text isn't clear as to whether the `organization` parameter is optional. This can lead to people assuming the parameter isn't optional and doing `organization=username`, which will not work.
> Clarify instructions for /forks endpoint.

- enterprise/2.2/v3/orgs/hooks/index.html
The organization webhooks API on GitHub Enterprise still require the custom media type to be passed along with the request. This is noted for [v2.1](https://developer.github.com/enterprise/2.1/v3/orgs/hooks/) and below, but is missing for [v2.2](https://developer.github.com/enterprise/2.2/v3/orgs/hooks/).
This PR adds the tip to the static Enterprise 2.2 docs.
/cc @gjtorikian @github/docs-platform
> Adds the tip for preview media type for Enterprise 2.2

- content/v3/oauth.md
The exact same sentence is used in the previous paragraph to explain why oauth is preferred over basic auth
> duplicate sentence from paragraph above

- content/v3/users/administration.md
I noticed the verb + endpoints weren't rendering as `pre` tags:
This PR pushes them in by a couple of spaces.
/cc @github/platform
> Indent verbs all the way

- content/v3/activity/events/types.md
I'd assumed that the name under "Event name" was used in the `type` field of the event object but I was wrong. There is a hint that the camel-cased variant is used on the Events page in the form of `"type": "Event"` but it's best to be explicit, anyway. Anyone who uses the API will notice immediately, anyway.
> Clarify differences between Events API and webhooks

- content/v3/issues/comments.md
`/repos/:owner/:repo/issues/:number/comments` supports `since` (but not `sort` or `direction`, which seem to be fixed as created/ascending).
> "Comments on an issue" endpoint supports 'since'

- content/libraries.md
Added a link in the libraries page to a scala implementation of the api ([Buhtig](https://github.com/mdread/buhtig))
> Add new library for Scala, Buhtig

- config.yaml
Haha, finally got Ruby working on Windows.
This ensures a consistent authoring model, since everyone likes consistency.
|           good           |               bad              |
|-------------------------|-----------------------------|
|![image][left home] | ![image][right home]  |
[left home]: https://cloud.githubusercontent.com/assets/4105066/9944079/6138de36-5d85-11e5-9b58-662e478294a3.png
[right home]: https://cloud.githubusercontent.com/assets/4105066/9944151/be4358ae-5d85-11e5-8a67-fd56c2925c91.png
> Set the encoding to be used to utf-8

- content/changes/2013-08-20-search-api-improvements.md
- content/changes/2013-10-04-oauth-changes-coming.html
- content/changes/2014-05-19-deployments-api-updates.md
- content/changes/2014-09-12-changing-organization-feeds.md
- content/changes/2014-10-21-deployment-webhook-payload-changes.md
- content/changes/2015-06-11-pages-a-records.md
- content/v3.md
This separates the code blocks from the text and encourages
authoring as-is, since no escaping is necessary.
> Use better code blocks for syntax highlighting

- content/guides/discovering-resources-for-a-user.md
Added a missing subject to a sentence.
I chose *__we__'ll* instead of *__we__ will* because it is more common in this repository.
> Fix minor grammatical issue on a help page

- content/webhooks/configuring/index.md
Although the ngrok site is hosted at https://ngrok.com/ the public socket URLs it creates are of the format: `*.ngrok.io` rather than `*.ngrok.com`
> ngrok public URLs use ngrok.io domain

- README.md
* Specify the proper required Ruby version (2.2, rather than 1.9)
* Remove mention of autocompile, because it’s replaced with [guard-nanoc](https://github.com/guard/guard-nanoc)—and this repo is already using it anyway.
* Fix name (Nanoc vs nanoc)
> Fix README for Nanoc 4

- content/v3/auth.md
There may be a better way to do this, but https://developer.github.com/v3/auth/#basic-authentication does not correctly show the < inside the command line block.
> Corrected display of <

- .travis.yml
- script/cibuild
- script/test
A few things:
* Travis' caching mechanism was conflicting with `script/bootstrap`. The Travis YML has changed to cache both the gems and the node modules required by this site.
* Some new test changes necessitated changes in `script/cibuild` for Travis.
> Update Travis configuration

- content/v3/enterprise/management_console.md
In a recent customer question (in Front, so no thread available :frowning:) @davideg @brainstarr and I found that the example commands were missing a `-k` flag, and needed to be via https. The steps we documented for the customer are [here](https://gist.github.com/brainstarr/03aabb95bd4154ea3da6).
I'm not sure if this needs to be updated for each example on the page, but I can test that if needed.
I also removed a version number from a link to the Enterprise docs so that it redirects to the latest version.
/cc @github/api, @github/docs-platform, and @github/copy
> Add -k flag and https to 2 examples

- content/v3/issues/milestones.md
The docs referred to a `due_date` field which doesn't exist. The field is actually `due_on`.
Side note: The API does not return the referenced `completeness` field although apparently we can sort on it. I assume `completeness` is an internal field equals `open_issues` / (`open_issues` + `closed_issues`), and which is not exposed via the API.
> Corrected milestone ref from due_date to due_on

- content/v3/repos/releases.md
Since [Media Type revision 671520376][1] (15 July 2015) the list has been removed.
This links to a more authorative source.
[1]: https://en.wikipedia.org/w/index.php?title=Media_type&oldid=671520376
> Fix link to list of media types

- content/guides/basics-of-authentication.md
Found a spelling mistake -
`posible` > `possible`
> Fixes typo in guides

- content/guides/getting-started.md
kramdown does not handle link targets with line breaks, apparently.
> Fix link to .gitignore templates

- enterprise/2.0/guides/managing-deploy-keys/index.html
- enterprise/2.1/guides/managing-deploy-keys/index.html
- enterprise/2.2/guides/managing-deploy-keys/index.html
- enterprise/2.3/guides/managing-deploy-keys/index.html
- enterprise/2.4/guides/managing-deploy-keys/index.html
The backport to 2.5 was done in https://github.com/github/developer.github.com/pull/1010.
This backports the same changes to the `guides/managing-deploy-keys/index.html` article to versions 2.0-2.4.
The change in the source files that this backports is in: https://github.com/github/developer.github.com/commit/cbf17ee3eedf43e5fd129045f365399101f20464
> Manual backport of change to Managing Deploy Keys article

- content/v3/pulls.md
["Labels, assignees, and milestones"](https://developer.github.com/v3/pulls/#labels-assignees-and-milestones) should be its own section (and listed in the TOC) but it was showing up as a sub-section of "Merge a pull request (Merge Button)"
> Fix section header in API - Pull Requests doc

- .gitignore
- README.md
- Rakefile
This pull request creates a rake task for generating json payloads as files from the documentation. Having the payload as files is useful for code generations of data objects (i.e for languages where serialising JSON to existing objects is necessary).
> Add support for generating JSON from documentation

- content/guides/delivering-deployments.md
There was a small typo in the documentation - I went ahead and corrected it.
`You'll notice that this pattern is the exact same as when we you your CI statuses.` -> `You'll notice that this pattern is the exact same as those which we display in your CI statuses.`
Hope this helps!
> Documentation update

- content/v3/pulls/comments.md
* I interpreted it as if the example was showing how to make a commit comment on a commit in the PR. This makes it clearer that its a review comment on the unified diff.
> Clarifying usage of commit_id in comment example

- content/v3/pulls/comments.md
This update partially reverts a change from #1020 - changing the description of the `commit_id` value in the Pull Request comment's input table.
In #1020, it was [suggested](https://github.com/github/developer.github.com/pull/1020/files#r54633578) that a note could convey _when_ the `commit_id` should be the latest commit, since:
> in some cases users may want to comment on a previous version of the PR via the API. In order to do so, they will need to pass a `commit_id` that's not equal to the "latest commit of the pull request".
/cc @tomasbjerre: I overlooked this in #1020, the note is still here, I just reverted the change to the table.
> Changes `commit_id` description back to original

- content/v3/issues.md
Found inconsistent mistakes to request and response examples -
part of request (in `Create an issue` & `Edit an issue`)
```json
"labels": [
"Label1",
"Label2"
]
```
part of response (in`Create an issue` & `Edit an issue`)
```json
"labels": [
{
"url": "https://api.github.com/repos/octocat/Hello-World/labels/bug",
"name": "bug",
"color": "f29513"
}
],
```
I changed request examples.
> Fix inconsistent req/res in issues.md

- content/libraries.md
Wrapper for GitHub API v3 as move from `Scion` to `FlexyProject` and offer now both PHP5.6 and PHP7 versions.
Link to repository as been updated.
> Updating GitHub API v3 wrapper link and name

- lib/changes_helper.rb
This orders first by `created_at` descending (newest first) and then by `title` ascending.
This should not be TOO surprising, and doesn't trigger 600+ changed lines after each commit.
(Feed readers should also like this a little better than changing up the ordering every time)
Let me know what you think.
> Order the 'changes' in a consistent way

- content/search/search-index.json
This ensures that after deployment the `search-index.json` is in a consistent state so the order can be reproduced build after build.
Inspired by https://github.com/github/developer.github.com/commit/821c7fbbd08ffd8706d1a60370a50cb21f29af46#diff-3e285797a87ae049427e9c86def110cb
> Serialize the `search-index.json` alphabetically

- content/v3/activity/events/types.md
- Fixed ordering of keys (just for organisation, really)
- Added `added`, `modified`, `removed`, and `committer` keys
- Fixed incorrect key `sha`, should be `id`
> Updated "push" event payload to match

- lib/strings.rb
This is a follow up to #1032, where the backslashes and quotes were escaped once by our code, and once by `JSON.generate()`.
Once is of course enough.
This cleans up the resulting JSON which allows us to pack more awesomeness in the data we send to the client! :boom:
> Don't escape the special characters for the JSON output

- lib/strings.rb
This reduces all double spaces because it cleans up after `strip_html` turned the document into regular text.
> Reorder squish(), so it is performed on simple text

- content/v3/oauth.md
In the [OAuth 2 spec](https://tools.ietf.org/html/rfc6749#section-3.3), it says that:
> The value of the scope parameter is expressed as a list of space-delimited, case-sensitive strings.
I tested this, and it seems like GitHub's OAuth implementation allows both spaces (to be spec compliant) and commas to delimit scopes. I think we should change the documentation so it matches the spec, and what people expect. 
Otherwise the documentation will force people developing OAuth clients to make a deviation just for GitHub, even when it's not needed.
> Changed comma to space in accordance with OAuth spec

- content/v3/git/commits.md
- content/v3/git/tags.md
- content/v3/repos/commits.md
- content/v3/users/gpg_keys.md
@alfhenrik pointed out over in [this issue](https://github.com/octokit/octokit.net/issues/1252#issuecomment-223782044) that the preview headers for GPG Keys are not consistent:
- `application/vnd.github.cryptographer-preview` as per [the announcement blog post](https://developer.github.com/changes/2016-04-04-git-signing-api-preview/)
- `  application/vnd.github.cryptographer-preview+sha` as per [the current docs](https://developer.github.com/v3/users/gpg_keys/)
I tested both values with a valid token and they fine, but this PR normalizes the docs to use `application/vnd.github.cryptographer-preview` to be consistent with most of our other preview APIs.
Let me know if anything is unclear here.
> GPG Keys documentation specify multiple potential Accept values

- lib/responses/issues_and_prs.rb
- lib/responses/user.rb
I saw that the original user was not in the `assignees` list, and that the users in the `assignees` list weren't consistent.
This updates (merges) the `USER` with itself, updating all fields with the block. (if anyone knows of a nicer way, let me know)
This makes the data a little more realistic.
> Assignees rename fields

- content/guides/delivering-deployments.md
Change "Pull Request" to "pull request" when referring to an instance of a pull request and not Pull Requests as a feature.
> Fix capitalization for "pull request"
