github/developer.github.com

content/v3/issues/comments.md
Thanks @stephenfin for catching this!
=> Issue comments are issue comments, not pull request comments

enterprise/11.10.340/v3/enterprise/search_indexing/index.html, enterprise/2.0/v3/enterprise/search_indexing/index.html, enterprise/2.1/v3/enterprise/search_indexing/index.html
The search indexing API change applies to Enterprise 11.10.340, 2.0, and 2.1.
=> Add update from #745 to Enterprise docs

content/changes/2013-09-03-two-factor-authentication.md, content/guides/basics-of-authentication.md, content/guides/getting-started.md, content/v3/auth.md, content/v3/oauth.md, content/v3/oauth_authorizations.md
this is for https://github.com/github/github/pull/40509 and https://github.com/github/github/pull/40821
@jasonrudolph @pengwynn @tclem @gregose @ptoomey3
=> Changes to personal access tokens urls and dev apps urls

content/v3/issues.md
Add ```null``` to issue edition for removing current milestone
=> Update milestone edit Issue

content/changes/2015-06-24-breaking-changes-to-organization-permissions-are-now-official.md, content/guides/discovering-resources-for-a-user.md, content/v3/orgs.md, content/v3/orgs/members.md, content/v3/repos.md
/cc @pengwynn @gjtorikian @github/platform
=> Fix moondragon merge conflicts

content/changes/2015-01-19-an-integrators-guide-to-organization-application-policies.md
Was reading this one today and came across a couple typos.
=> Fix typos in OAP integrators guide post

content/libraries.md
https://github.com/gitskarios/GithubAndroidSdk
=> Add Github Android SDK library

content/v3/enterprise/management_console.md
I know it's subtle, but a nice little heads up about needing to run this after settings changes is nice. maybe!
:tada: Open Source Friday! :tada:
=> heads up for POST configure

content/v3/enterprise/management_console.md
I know we warn about this in a tip in the top, but it's so subtle and easily missed. Is there any reason not to include this elsewhere? cc @leefaus who was helping me with this!
cc @github/docs or @gjtorikian
=> every curl needs optional s, and admin port

README.md
=> Changed the word setup to its verb form

content/v3/git.md
Aims to make Travis happy https://travis-ci.org/github/developer.github.com/builds/85739141
/cc @gjtorikian
=> Fix broken link to Git internals

content/v3/issues/events.md
"rename" was the only attribute followed by a colon, which is inconsistent. This PR fixes that.
It's my first time contributing to this repo, so I'm not sure if there are some other files that need to be generated/updated. I've looked around, and it doesn't seem that way (nor is it mentioned in CONTRIBUTING.md). But do let me know if I did something wrong.
=> Fix typo in events.md.

lib/changes_helper.rb
This PR has removed some code and replaced a ternary condition with `value if condition` syntax to be more in line with the other code in the same file.
=> minor code improvements

content/guides/traversing-with-pagination.md
Make regex better for pagination example octokit/octokit.rb#656
=> Improve regex for pagination example

content/v3/pulls.md
=> Clarify merge message description

content/v3/repos/collaborators.md
Updates default permmissions to reflect what team occipital has experienced on https://github.com/occipital/testrepodeleteme/settings/collaboration (which is an organization-owned repository)
```python
import requests
requests.put('https://api.github.com/repos/occipital/testrepodeleteme/collaborators/{}'.format('owockibot'), params={ 'permission' : 'pull' }, auth=("<user>","<pw>"))
```
yeilds 
Here is a cute baby animal picture for your troubles...
=> Updates default permmissions to reflect what team occipital has experienced

content/v3/activity/events/types.md
Reverts github/developer.github.com#1033
=> Revert "Updated "push" event payload to match"

content/changes/2016-04-18-new-webhook-actions-are-live.md
Title says enough in my opinion.
I noticed that there are five event types listed below the sentence that speaks of four.
=> Fixup for the 'new webhook actions are live' count

content/v3/activity/events/types.md
Reverts github/developer.github.com#1056
=> Revert "incorrect key for commit head"

README.md
I Added The ![](https://api.travis-ci.org/github/developer.github.com.svg) Tag! :smiley:
=> I Added The [Build|Passing] Tag! :smiley: 

content/v3/repos/invitations.md
This change makes it appear inside a code block, as it should be.
=> Fix formatting of Decline a repository invitation endpoint.

content/v3/oauth.md
If it's true or false, it's a boolean.
=> Use a more descriptive type for oauth.allow_signup
